config/routes.rb
Rails.application.routes.draw do
  mount Base::API => '/'

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/destroy' => 'users#destroy'

  # メンバー
  resources :members

  # チーム
  resources :teams
  get '/teams/:id/delete' => 'teams#destroy'

  post '/team_members' => 'team_members#create'
  get '/team_members/:id/delete' => 'team_members#destroy'

  # 説明系
  get '/infos/index' => 'infos#index'

  # 管理
  get '/admin/import_form' => 'admin#import_form'
  post '/admin/import' => 'admin#import'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FFS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{ src: "//code.jquery.com/jquery-3.2.1.slim.min.js", integrity: "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", crossorigin: "anonymous" }
    %script{ src: "//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js", integrity: "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", crossorigin: "anonymous" }
    %script{ src: "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", crossorigin: "anonymous" }
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      %a.navbar-brand{href: '/' }
        FFS
      %ul.navbar-nav.mr-auto
        %li.nav-item
          =link_to 'メンバー一覧', members_path, { class: 'nav-link' }
        %li.nav-item
          =link_to 'チーム一覧', teams_path, { class: 'nav-link' }
        %li.nav-item
          =link_to 'FFSについて', infos_index_path, { class: 'nav-link' }

      %button.navbar-toggler{type:"button", 'data-toggle': "collapse", 'data-target': "#navbarNavAltMarkup", 'aria-controls': "navbarNavAltMarkup", 'aria-expanded': "false", 'aria-label': "Toggle navigation"}
        %span.navbar-toggler-icon
      - if session['login']
        %div.login
          %ul.navbar-nav
            %li.nav-item.dropdown.login-user
              %a.nav-link.dropdown-toggle#navbarDropdownMenuLink{"data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": "false"}
                %span
                  %img{src: session['login']['image']}
              %div.dropdown-menu{"aria-labelledby": "navbarDropdownMenuLink"}
                %span
                  %strong= session[:login]['email']
                  でログイン中
                %div.dropdown-divider
                = link_to 'ログアウト', users_destroy_path, {class: "dropdown-item"}
    %div.container-fluid
      %div.row
        %main
          -flash.each do |type, msg|
            %div{class: "alert alert-#{type}"}= msg

          = yield

app/views/layouts/nologin.html.haml
!!!
%html
  %head
    %title FFS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    %script{ src: "//code.jquery.com/jquery-3.2.1.slim.min.js", integrity: "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", crossorigin: "anonymous" }
    %script{ src: "//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js", integrity: "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", crossorigin: "anonymous" }
    %script{ src: "//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js", integrity: "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", crossorigin: "anonymous" }
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      %a.navbar-brand{href: '/' }
        FFS
      %button.navbar-toggler{type:"button", 'data-toggle': "collapse", 'data-target': "#navbarNavAltMarkup", 'aria-controls': "navbarNavAltMarkup", 'aria-expanded': "false", 'aria-label': "Toggle navigation"}
        %span.navbar-toggler-icon
      - if session['login']
        %div.login
          = session['login']
          = link_to 'ログアウト', users_destroy_path
    %div.container-fluid
      %div.row
        %main.col-sm-9.offset-sm-3.col-md-10.offset-md-2.pt-4
          = yield