config/routes.rb
Rails.application.routes.draw do
  mount Base::API => '/'

  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get '/users/destroy' => 'users#destroy'

  # メンバー
  resources :members

  # チーム
  resources :teams
  get '/teams/:id/delete' => 'teams#destroy'

  post '/team_members' => 'team_members#create'
  get '/team_members/:id/delete' => 'team_members#destroy'

  # 説明系
  get '/infos/index' => 'infos#index'

  # 管理
  get '/admin/import_form' => 'admin#import_form'
  post '/admin/import' => 'admin#import'
end

app/models/member.rb
class Member < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  has_one :member_ffs, class_name: "MemberFFS"
  has_many :member_stresses

  def team_member(team_id)
    TeamMember.find_by member_id: id, team_id: team_id
  end

  def self.create_by_ethos!(data)
    m = new_by_ethos(data)
    m.save!
    m
  end

  def self.new_by_ethos(data)
    # emailを主キーに上書き
    m = find_or_initialize_by(
      email: data['メールアドレス']
    )
    m.key = data['社員番号']
    m.name = data['氏名']
    m.name_en = data['氏名(英語)']
    m
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show]

  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to root_path
    end
end

app/views/members/_ffs_factor_point.html.haml
-if type_name.include?(name)
  %strong{class: type_name.start_with?(name) ? 'mark text-primary' : nil}= point
-else
  = point

app/views/members/_ffs_stress_point.html.haml
-if point >= 13 || point <= 3
  %strong{class: 'mark text-danger'}= point
-else
  = point

app/views/members/_list_table.html.haml
- # デフォルト
- # 削除列を用意
- use_remove = defined?(use_remove) ? use_remove : false;
- # ストレス表示
- use_stress = defined?(use_stress) ? use_stress : false;
- # 平均 team 必須
- use_average = defined?(use_average) ? use_average : false;

%table.table.table-hover
  %thead
    %tr
      %th 名前
      %th A: 凝縮性
      %th B: 受容性
      %th C: 弁別性
      %th D: 拡散性
      %th E: 保全性
      %th 91 Type
      %th= link_to "4 Type", infos_index_path(anchor: "4_type")
      - if use_stress
        %th ストレス
        %th ストレス履歴
      - if use_remove
        %th 削除
  %tbody
    - @members.each do |member|
      %tr
        %td
          = link_to member.name, member_path(member.id)
          %br
          %span.sub= (member.email)
        %td
          =render 'members/ffs_factor_point', name: 'A', type_name: member.member_ffs["91_type"], point: member.member_ffs.a
        %td
          =render 'members/ffs_factor_point', name: 'B', type_name: member.member_ffs["91_type"], point: member.member_ffs.b
        %td
          =render 'members/ffs_factor_point', name: 'C', type_name: member.member_ffs["91_type"], point: member.member_ffs.c
        %td
          =render 'members/ffs_factor_point', name: 'D', type_name: member.member_ffs["91_type"], point: member.member_ffs.d
        %td
          =render 'members/ffs_factor_point', name: 'E', type_name: member.member_ffs["91_type"], point: member.member_ffs.e
        %td= member.member_ffs['91_type']
        %td= member.member_ffs['4_type']
        - if use_stress

          %td
            - if member.member_stresses.last.present?
              %span.main
                =render 'members/ffs_stress_point', point: member.member_stresses.last.point
              %span.sub= '[ ' + member.member_stresses.last.diagnostic_at.strftime('%Y年%m月') + ' ]'
          %td
            %ul.stresses
              - if member.member_stresses.last.present?
                - member.member_stresses.each do |stress|
                  %li
                    %span.main
                      =render 'members/ffs_stress_point', point: stress.point
                    %span.sub= '[ ' + stress.diagnostic_at.strftime('%Y年%m月') + ' ]'
        - if use_remove
          %td
            =link_to '/team_members/' + String(member.team_member(@team.id).id) + '/delete', onclick: "return confirm('削除して良いですか？')" do
              %span.glyphicon.glyphicon-trash{"aria-hidden": "true"}
    - if use_average
      %tr
        %td 平均
        %td= team.a_avg
        %td= team.b_avg
        %td= team.c_avg
        %td= team.d_avg
        %td= team.e_avg
        %td
        %td
        - if @is_manager
          %td= team.stress_avg
          %td
        - if use_remove
          %td

app/views/members/index.html.haml
%h1 メンバー一覧
=render 'members/list_table', use_stress: @is_manager

app/views/members/show.html.haml
%h1= @member.name + ' - (' + @member.member_ffs['91_type'] + ')'

%h2 因子

%div.ml-5.mr-5
  %canvas#memberLineChart{width: "400", height: "400"}

:javascript
  $(function() {
    var datasets = [{
      label: "#{@member.name}\(#{@member.member_ffs['91_type']}\)",
      data: [#{@member.member_ffs.a}, #{@member.member_ffs.b}, #{@member.member_ffs.c}, #{@member.member_ffs.d}, #{@member.member_ffs.e}],
      lineTension: 0,
      fill: false,
      backgroundColor: '#a6cee3',
      borderColor: '#a6cee3'
    }];
    var labels = ['A 凝縮性', 'B 受容性', 'C 弁別性', 'D 拡散性', 'E 保全性'];
    var data = {
      labels: labels,
      datasets: datasets,
    };
    var ctx = document.getElementById("memberLineChart").getContext("2d");
    var options = {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: true,
            min: 0,
            max: 20
          }
        }]
      },
      responsive: true,
      maintainAspectRatio: false
    };
    var lineChart = new Chart(ctx, {
      type: 'line',
      data: data,
      options: options
    });
    lineChart.canvas.parentNode.style.height = '400px';
  });

%h2 因子概要

%p.mt-5.ml-5.mr-5= @member.member_ffs.description

-if @is_manager
  %h2 ストレス

  %div.ml-5.mr-5
    %canvas#stressLineChart{width: "400", height: "400"}

  - # 1つしかデータがない場合にグラフの左にひっつくのを避けるために開始と終了に空値を入れる
  - data = [nil]
  - labels = ['']

  - @member.member_stresses.order(diagnostic_at: "ASC").each do |stress|
    - data << [stress.point]
    - labels << [stress.diagnostic_at]

  - # 1つしかデータがない場合にグラフの左にひっつくのを避けるために開始と終了に空値を入れる
  - data << nil
  - labels << ''

  :javascript
    $(function() {
      var datasets = [{
        label: "ストレス",
        data: #{data.to_json.html_safe},
        lineTension: 0,
        fill: false,
        backgroundColor: '#a6cee3',
        borderColor: '#a6cee3'
      }];
      var labels = #{labels.to_json.html_safe};
      var data = {
        labels: labels,
        datasets: datasets,
      };
      var ctx = document.getElementById("stressLineChart").getContext("2d");
      var options = {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true,
              min: 0,
              max: 20
            }
          }]
        },
        responsive: true,
        maintainAspectRatio: false
      };
      var lineChart = new Chart(ctx, {
        type: 'line',
        data: data,
        options: options
      });
      lineChart.canvas.parentNode.style.height = '400px';
    });

%h2 ストレス要因
%ul
  -@member.member_ffs.ffs.each do |ffs|
    %li
      %strong= ffs.name
      %ul
        - JSON.parse(ffs.stresser).each do |s|
          %li= s